### ISSUE TITLE
Automatically open next after last watched video

### ISSUE THREAD

**Issue by Defelo** [Bootstrap-Academy/Bootstrap-Academy#10]
On the profile page, when clicking on a course, redirect to the first video which has not yet been watched.

API endpoint to get the relevant video: [`GET /skills/courses/{course_id}/next_unseen`](https://api-test.bootstrap.academy/skills/docs#/course/next_unseen_lecture_courses__course_id__next_unseen_get)

## Acceptance criteria
- [x] When clicking on a course on the profile page, redirect to the video returned by the endpoint mentioned above.

**Comment by JohKei** [comment]
I will have a look into this today

**Comment by JohKei** [comment]
Hello @Defelo . Upon looking into this issue, I came across a minor problem that would require a backend change.

The 'watch' lecture component route requires the 'section' ID as well as the lecture ID in the route parameters. However, the '[/courses/{course_id}/next_unseen](https://api-test.bootstrap.academy/skills/docs#/course/next_unseen_lecture_courses__course_id__next_unseen_get)' route only returns the lecture ID.

Nevertheless, I will create a working pull request later today. For now, the solution is to use the '[/courses/{course_id}](https://api-test.bootstrap.academy/skills/docs#/course/get_course_details_courses__course_id__get)' route to retrieve the course details, obtain the section ID that contains the lecture ID from the '[/courses/{course_id}/next_unseen](https://api-test.bootstrap.academy/skills/docs#/course/next_unseen_lecture_courses__course_id__next_unseen_get)' route, and then navigate to the 'watch' route.

**Comment by Defelo** [comment]
Hi @JohKei, I've updated the endpoint to include both the lecture and the section now.

**Comment by JohKei** [comment]
> Hi @JohKei, I've updated the endpoint to include both the lecture and the section now.

Okay. I just pushed the change. It should be fine now.

**Comment by JohKei** [comment]
The PR for this issue is ready for review, in case you were not aware.
