### ISSUE TITLE
Missing webinar information

### ISSUE THREAD

**Issue by Defelo** [Bootstrap-Academy/Bootstrap-Academy#11]
Webinar entries in the calendar are currently lacking a lot of information (even the description is not displayed). When clicking on the event summary on the bottom right of the page under "Upcoming Events", a dialog should open which contains all relevant information about the webinar.

![image](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/41747605/4f0c44a7-994f-46f0-b3c9-ab33fd317b43)

## Acceptance criteria
- [x] When clicking on the webinar summary, a dialog should open, containing the following information:
    - [x] Name
    - [x] Description
    - [x] Skill and parent skill (both with links to the skill tree)
    - [x] Start and end timestamps (and duration)
    - [x] Price
    - [x] Instructor name, avatar and rating
    - [x] Link (if the user has access to the link)
    - [x] Admin link (if the user has access to the admin link)
    - [x] Timestamp when this webinar has been created
    - [x] Number of registered participants and maximum capacity
    - [x] A button to book the webinar (if it is bookable)
- [x] In the webinar summary itself, display the skill *name* instead of its id.

**Comment by Defelo** [comment]
Since no one is assigned to this ticket and there are no related open pull requests, I don't think anyone is working on this

**Comment by JohKei** [comment]
Good Evening @Defelo . 
While I was looking into this issue, I ran into a question regarding the following points:

- Link if user has access
- Admin link if user has access

Because right now, both links are always available, what are the user access and admin access conditions to display them?

**Comment by Defelo** [comment]
The admin link is only available if the user has created this webinar or if the user is an admin. And the normal link is available to anyone who has booked the webinar (and of course to the webinar creator and admins). If the user does not have access to any of those, the backend simply returns `null` for them, so you just have to check if the link is `null` or not.

**Comment by JohKei** [comment]
Hello @Defelo . I just opened a Pull-request for this Issue. I hope it's fine
