### ISSUE TITLE
Leaderboard repeating

### ISSUE THREAD

**Issue by TheMorpheus407** [Bootstrap-Academy/Bootstrap-Academy#115]
### Bootstrap Academy username

Morpheus

### What happened?

If you scroll through the leaderboard, it repeats itself after finishing. This shouldnt be the case (obviously)

**Comment by Lauritz-Tieste** [comment]
I could not reproduce a repeating leaderboard. Does this error still occur in the latest version? Can you send a screenshot or a video?
