### ISSUE TITLE
Scrolling the leaderboard

### ISSUE THREAD

**Issue by TheMorpheus407** [Bootstrap-Academy/Bootstrap-Academy#116]
### Bootstrap Academy username

Morpheus

### What happened?

When scrolling the leaderboard, there is a scrollbar within the webpage. When not hovering the scrollable element, one scrolls the website.
Instead of only the element being scrollable, one should always scroll the entire webpage for the leaderboard.
[Reference](https://bootstrap.academy/challenges/leader-board/?selectedButton=0&selectedLanguage=python)

**Comment by Lauritz-Tieste** [comment]
@TheMorpheus407 Is [PR #201](https://github.com/Bootstrap-Academy/frontend/pull/201) the change you wanted to achieve with the issue?

**Comment by Defelo** [comment]
Fixed in https://github.com/Bootstrap-Academy/frontend/pull/201
