### ISSUE TITLE
Sorting of self hosted courses

### ISSUE THREAD

**Issue by TheMorpheus407** [Bootstrap-Academy/Bootstrap-Academy#117]
Self hosted courses will always load the video the user previously accessed.
Example:
Python pentesting.
I click on the course and then on video no. 4, I will get served the first video. Going to video 5 will then load video 4.

**Comment by LennartKDeveloper** [comment]
I would like to try this one :)

**Comment by BugsSindFeatures** [comment]
I would like to do this.
