### ISSUE TITLE
Refill button content overflow

### ISSUE THREAD

**Issue by louis-develop** [Bootstrap-Academy/Bootstrap-Academy#121]
### Bootstrap Academy username

Louisokk

### Contact Details

louisrost.bau@gmail.com

### What browsers are you seeing the problem on?

Chrome

### What happened?

<img width="191" alt="image" src="https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/154506054/88559df1-f877-41cc-abc7-845f9abceac9">
Container of refill button is missing an overflow-hidden.

**Comment by Lauritz-Tieste** [comment]
Since https://github.com/Bootstrap-Academy/frontend/pull/218 this button no longer exists in the form. The error has always annoyed me, but now it no longer appears in the latest version. This issue can be closed.
