### ISSUE TITLE
Nuxt in 404 page

### ISSUE THREAD

**Issue by SpotlightForBugs** [Bootstrap-Academy/Bootstrap-Academy#125]
### Bootstrap Academy username

sfb

### Contact Details

academy@spotlightforbugs.eu

### What browsers are you seeing the problem on?

Other (please specify below)

### What happened?

All browsers

![IMG_0907](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/73603712/9264bb88-b464-48a1-9379-c0dbaf9187da)

**Comment by SpotlightForBugs** [comment]
https://bootstrap.academy/-%5E11

**Comment by SpotlightForBugs** [comment]
![image](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/73603712/6343aff4-cc59-4f90-be2b-629254921092)

**Comment by JoeD84** [comment]
I would like to solve this one for the Hackaton.

It seems Nuxt is displaying Default Errors. I would add a custom Error Page as described here: 
[https://nuxt.com/docs/getting-started/error-handling](Error Handling)

This would be a first draft:
![Image](https://github.com/user-attachments/assets/0441a0d8-c18e-458c-8f95-3d941fafae7c)

**Comment by CuriousExile** [comment]
I did take a quick look at the ticket and came to the same conclusion, that we would need a costume error page.
