### ISSUE TITLE
Montly Membership MorphCoin payment "graphic glitches"

### ISSUE THREAD

**Issue by Mattias-R** [Bootstrap-Academy/Bootstrap-Academy#127]
### Bootstrap Academy username

studInfo

### What browsers are you seeing the problem on?

Chrome

### What happened?

On the page https://bootstrap.academy/subscription the slider which displays the credit card and if it is yearly or monthly has some graphic glitches. If you hover over the edges on the left or right side, the transition animation gets stuck.

![glitch](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/42864156/0b841394-e3da-4d51-b412-e0eacc28f00d)

It doesn't happen immediately, you have to play around. This probably occures because the size shrinks and if the cursor is on a bad spot, it does not know if it should continue the transition.

![image](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/42864156/0c3ceac0-8ab2-4ef2-8164-f4dfacf3c1f2)

here is a video of the bug occurring

https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/42864156/165fac14-4bcf-4a70-af9f-470836984153

**Comment by Lauritz-Tieste** [comment]
Since https://github.com/Bootstrap-Academy/frontend/pull/211 this button no longer exists. This issue can be closed.
