### ISSUE TITLE
Set Code for C in Coding Challenges does not contain the import

### ISSUE THREAD

**Issue by TheMorpheus407** [Bootstrap-Academy/Bootstrap-Academy#140]
### Bootstrap Academy username

Morpheus

### Contact Details

kontakt@the-morpheus.de

### What happened?

Example: [https://bootstrap.academy/challenges/e5f6f57b-43d6-4172-b451-4ec4fb464c33/fd8831a2-c513-4c29-8827-17a3f8b9c082?codingChallenge=8531ddb4-6f15-4896-965b-2383fefd76ab](https://bootstrap.academy/challenges/e5f6f57b-43d6-4172-b451-4ec4fb464c33/fd8831a2-c513-4c29-8827-17a3f8b9c082?codingChallenge=8531ddb4-6f15-4896-965b-2383fefd76ab)

When switching to C Code and updating we get:
```
int main() {
  char name[32];
  scanf("%s", name);
  printf("Hello, %s!", name);
  return 0;
}
```

this is a preset code, that should work and should how to read the inputs and produce simple outputs.
This will however result in an error.

The example code has to be changed to
```
#include<stdio.h>

int main() {
  char name[32];
  scanf("%s", name);
  printf("Hello, %s!", name);
  return 0;
}
```

**Comment by Defelo** [comment]
Solved in https://github.com/Defelo/sandkasten/pull/372, deployed in https://github.com/Bootstrap-Academy/infrastructure/commit/de7126c705a587b70ecc1f84895d781dd66a831f
