### ISSUE TITLE
Page crash / infinity loop on Challenges page

### ISSUE THREAD

**Issue by Lauritz-Tieste** [Bootstrap-Academy/Bootstrap-Academy#149]
### Bootstrap Academy username

LauritzTieste

### Contact Details

hello@lauritz-tieste.de

### What browsers are you seeing the problem on?

Other (please specify below)

### What happened?

All Chrome based browsers (here: Vivaldi). Also happening in Chrome, Arc Browser, Brave, MS-Edge

https://github.com/user-attachments/assets/d6a6411a-e297-457b-a640-758394dd278d

I can't explain the error. I noticed it several months ago. There could be an infinity loop somewhere. If you have any questions, just leave a comment. Only happening in the local test instance.

Error message that was spammed about 10,000 times
```
warn [Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead. 
  at <Select key=0 label="Category" id="select-category"  ... > 
  at <Challenge data=undefined > 
  at <AsyncComponentWrapper data=undefined > 
  at <Edit[challenge] onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {} > > 
  at <Anonymous key="/challenges/edit-9cd0bdbc-7d02-4f82-b7fa-6f52637212c4()" vnode= {} route= {}  ... > 
  at <BaseTransition onAfterLeave= [leer] mode="out-in" appear=false  ... > 
  at <Transition onAfterLeave= [leer] name="page" mode="out-in" > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <Inner ref=Ref< Proxy(Object) {} > > 
  at <LayoutLoader key="inner" layoutProps= {} name="inner" > 
  at <NuxtLayoutProvider layoutProps= {} key="inner" name="inner"  ... > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="layout" mode="out-in" > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>
```

**Comment by Lauritz-Tieste** [comment]
@Defelo Can you move this to the Tickets, so somebody from the hackathon can solve it?

**Comment by Lauritz-Tieste** [comment]
@Defelo Can you move this to the tickets, so somebody from the hackathon can fix it?

**Comment by eremia2001** [comment]
Hey , i would like to be assigned on this ticket .

**Comment by eremia2001** [comment]
brauche ich hierfür einen admin account oder  wie genau kann ich diesen Bug nachmachen ?

**Comment by Lauritz-Tieste** [comment]
Yes, an admin account is required for this. You can simply write @Defelo.
