### ISSUE TITLE
Matching repeating

### ISSUE THREAD

**Issue by NilocLP** [Bootstrap-Academy/Bootstrap-Academy#152]
### Bootstrap Academy username

Niloc

### Contact Details

Discord: nil0c_

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

For test purpose, I created a matching quiz inside the [HTML5 course](https://bootstrap.academy/courses/html5_fuer_anfaenger).
When going to the Matching Section now, my matching is displayed multiple times.

![Image](https://github.com/user-attachments/assets/28d2682b-5f86-4f3e-abae-e007043b6672)

**Comment by Lauritz-Tieste** [comment]
I think this is partially closed in https://github.com/Bootstrap-Academy/frontend/pull/291

**Comment by NilocLP** [comment]
Didn't find it under the Issue you mentioned: [Bootstrap-Academy/frontend#291](https://github.com/Bootstrap-Academy/frontend/pull/291)

Just found recommendations to hide empty matchings & quizzes.

**Comment by Lauritz-Tieste** [comment]
`pages/courses/[id]/index.vue` Line 84

I removed the for loop
