### ISSUE TITLE
Skilltree: Circular progress bars for skill icons

### ISSUE THREAD

**Issue by Defelo** [Bootstrap-Academy/Bootstrap-Academy#17]
#### Problem Description:
To enhance user engagement and provide a tangible representation of progress, we aim to introduce a visual enhancement to the skill tree nodes. This visual representation will provide clear cues on the user's progress in each skill without relying on colors, which are already reserved for bookmarks.

#### Objective:
Visually represent the user's progression in the skill tree for each node and sub-node without interfering with the existing skill tree structure or functionality.

#### Functional Requirements:

- [ ] **Default State**: Each skill and subskill node should have a regular icon with a single border, representing no XP gained or level 0.
  
- [ ] **Progressive States**: As the user gains XP and progresses in levels, the node's visual representation should evolve based on the described levels (25, 42, and 50).

#### Functional Requirements:

- [ ] **Appearance**: Starting from Level 25, a dotted border should surround the original border of the node. This design should be consistent for all nodes and sub-nodes.

#### Functional Requirements:

- [ ] **Appearance**: From Level 42 onwards, add four evenly spaced segments around the node's dotted border to give a clear indication of progress.

#### Functional Requirements:

- [ ] **Flame Animation**: Upon reaching Level 50, which is the maximum level, a subtle 2D burning flame effect should emerge behind the node and its borders. This flame should be colored identically to the borders and should symbolize the user's mastery over the skill.
  
- [ ] **Subtlety**: The flame effect should be gentle and continuous, without being too animated or disturbing.
  
#### Non-Functional Requirements:

- [ ] **Responsive Design**: Ensure that these visual modifications are adaptive and render correctly across varied screen sizes and devices. Additionally, conduct tests for appearance and animations across different browsers to ensure universal compatibility.
  
- [ ] **Performance Optimization**: 
   - [ ] Use lightweight images or SVGs combined with CSS transitions for smooth and efficient animations.

#### Dependencies:
- None for this feature. However, it's crucial to ensure that these visual changes do not conflict with existing functionalities, especially the color-coded bookmarks.

#### Notes:
- The primary goal is to provide an engaging visual feedback mechanism without altering the core functionalities or the data structure of the skill tree.
  
- All modifications should adhere to the current database schemas and the existing skill tree structure.

**Comment by LadonFire** [comment]
If it's ok, because I'm also doing the chat UI mockup, I would also like to tackle this project with a team consisting of two other people as part of the hackathon.

**Comment by Lauritz-Tieste** [comment]
I will try this
