### ISSUE TITLE
Months are not translated in the profile

### ISSUE THREAD

**Issue by TheMorpheus407** [Bootstrap-Academy/Bootstrap-Academy#18]
### Bootstrap Academy username

Morpheus

### Contact Details

kontakt@the-morpheus.de

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

![image](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/22853222/058a9d99-ee92-4a09-9b19-d0bf4618e96f)

Months are not translated in the profile page https://bootstrap.academy/profile

## Acceptance criteria
- [x] When visiting the profile, the months should be translated in the according language chosen by the user
- [x] When editing the profile, the months should be translated in the according language chosen by the user

**Comment by FabulousCodingFox** [comment]
Should the translation directly happen in the convertTimestampToDate() function? This would make the overall codebase less janky and also work on other subpages, but increaseses complexity. Is this only needed in on the /profile page?

**Comment by Defelo** [comment]
It looks like this is needed everywhere the `convertTimestampToDate` function is used. But in the calendar we already have translations for months (and weekdays), so maybe we could move this functionality into `convertTimestampToDate` and refactor the calendar to fix this.
