### ISSUE TITLE
You can rate a webinars too if its cancelled

### ISSUE THREAD

**Issue by TheMorpheus407** [Bootstrap-Academy/Bootstrap-Academy#22]
### What browsers are you seeing the problem on?

Chrome

### What happened?

You can rate a webinarstoo if its cancelled.

![image](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/22853222/6e66f96b-f541-4d41-9eff-655d9ce16c3e)

## Acceptance criteria
- [ ] Cancelled Webinars should not display a rating pop up window

**Comment by JohKei** [comment]
Is there a way to create a webinar for test purposes? I couldn't find a way to do this in either the frontend or the admin frontend.

**Comment by Defelo** [comment]
You should be able to create a webinar either in the skill tree or in the calendar if you have a specific skill level or admin privileges

**Comment by JohKei** [comment]
Hello @Defelo.

To me this Issue does not seem like a Frontend one.
Frontend is calling the route skills[/unrated](https://api-test.bootstrap.academy/events/docs#/ratings/list_unrated_unrated_get). There's currently no way in telling in the frontend, if the user was participating in That event or not.
My guess would be, that there might be a problem in the backend that they are still sending this Event as unrated even tough [/calendar/{event_id}](https://api-test.bootstrap.academy/events/docs#/calendar/cancel_event_calendar__event_id__delete) (cancel-event) has been called by the user.

**Comment by Lauritz-Tieste** [comment]
I could not reproduce the error. 

First, I created a webinar with my admin account and joined the webinar with a test account. I was able to rate the webinar after it had finished.

I then created another webinar and joined again with the test account. However, I then canceled the webinar with the admin account. After the actual duration of the webinar, there was NO RATING DIALOGUE.

**Comment by Lauritz-Tieste** [comment]
1. Ich habe "User" erstellt
2. "Admin" hat ein Webinar erstellt
3. "User" ist über `POST /webinars/{webinar_id}/participants` beigetreten
4. "Admin" hat das Webinar über `DELETE /calendar/{event_id}` gecanelt
5. Nachdem die Zeit des Webinars abgelaufen war, hat "User" über `GET /unrated` eine leere Liste erhalten.

Ich habe den Fehler im frontend auch nicht reproduzieren können und der im aktuellen Backend-Code ist eine Lücke für einen solchen Fehler auch nicht erkennbar.
