### ISSUE TITLE
Feature: User-Generated Matchings Creation

### ISSUE THREAD

**Issue by TheMorpheus407** [Bootstrap-Academy/Bootstrap-Academy#30]
### Bootstrap Academy username

Morpheus

#### Objective:
To democratize content creation on [bootstrap.academy](https://bootstrap.academy/), we aim to enable users (meeting the level requirement) to craft matchings for specific lectures or skills. This feature would be in line with the existing ability to create Multiple Choice Questions. The backend APIs are already in place for this.

#### Functionality:

- [x] **Creation Interface**:
   - [x] Enhance the "Create Task" button next to each lecture or skill to present an additional option, "Create Matching", alongside the pre-existing "Create Quiz" option.
   - [x] Design an interface that prompts users, upon selecting "Create Matching", to input items and their corresponding matches.
   - [x] Incorporate flexibility so users can introduce as many matching pairs as they deem necessary for the exercise.

- [x] **Database Integration**:
   - [x] Configure the backend to process and store the data when a user finalizes a matching exercise. This data should be associated with the specific lecture or skill in the database.

- [x] **Design & Styling**:
   - [x] Ensure the interface for matching creation harmonizes with the website's existing design aesthetics.

#### User Flow for Creation:

- [x] Upon navigating to a particular lecture or skill, users should find and be able to click the "Create Task" button.
  
- [x] Within the "Create Task" options, users should spot and be able to select the "Matching" option.
  
- [x] A user-friendly interface should allow users to input items and their corresponding matches for the matching exercise.
  
- [x] Post the addition of all required pairs, users should have a clear method to submit the matching.
  
- [x] Once submitted, the database should store the matching, making it accessible for the wider user base to engage with and solve.

#### Dependencies:
- Ensure that the new feature integrates seamlessly with the existing task creation functionalities and the platform's tech stack.

#### Notes:
- Prioritize user-friendliness in the creation interface, ensuring that the process is intuitive and straightforward. This will encourage more users to contribute to content creation.

**Comment by hamzazeus** [comment]
This looks cool. @TheMorpheus407. I have already worked on these matchings. Would you like me to contribute in it?

**Comment by Defelo** [comment]
Hi, @hamzazeus! Since no one is currently working on this ticket, would you still be interested in contributing?

**Comment by hamzazeus** [comment]
Hi @Defelo. Yes i have sent an email to @TheMorpheus407. With a video link attached. I have completed this module. Waiting to hear from him.
