### ISSUE TITLE
Display bug on the switch on the /subscription page

### ISSUE THREAD

**Issue by Lauritz-Tieste** [Bootstrap-Academy/Bootstrap-Academy#36]
### Bootstrap Academy username

Lauritz

### Contact Details

developer.lauritz-tieste@mail.de

### What browsers are you seeing the problem on?

Microsoft Edge (Version 117.0)

### What happened?

The Switch is not displayed correctly
![image](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/84938977/cf5717de-05ef-495c-b49a-741495673fd6)

**Comment by FabulousCodingFox** [comment]
Hello, I was not able to reproduce the bug with the latest Edge version (117.0). Are you using any plugins that might interfere with this? Darkmode, Tampermonkey, etc.?

**Comment by FabulousCodingFox** [comment]
The button was made with rem-based sizing, however the slider is offset using pixels. If theres a dimension mismatch this happens.

The easiest way to reproduce is to turn up the font size under windows accessibility settings to something > 100% (Im using 125%)
