### ISSUE TITLE
Display bug on the /challenges/leader-board/ page

### ISSUE THREAD

**Issue by FabulousCodingFox** [Bootstrap-Academy/Bootstrap-Academy#37]
### Bootstrap Academy username

FabulousFox

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### What happened?

When hovering over an entry, a horizontal scrollbar appears and the entry gets clipped off

![grafik](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/78906517/1cf03c94-9ce2-4a3e-93b8-cdc0fa6d9fa9)

**Comment by Lauritz-Tieste** [comment]
This was fixed by me with https://github.com/Bootstrap-Academy/frontend/pull/201. The changes will take effect once the current development version has been released.
