### ISSUE TITLE
Improve users page in admin dashboard

### ISSUE THREAD

**Issue by Defelo** [Bootstrap-Academy/Bootstrap-Academy#41]
Fix and improve the user administration page on https://bootstrap-academy-admin.pages.dev/dashboard/users.

### Search
Currently it is only possible to search by email, not by username. There is also a bug which causes the same users to appear more than once when searching repeatedly using the same search term.

![image](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/41747605/5a073f68-0e8a-442c-be0e-5f35fa79d98d)

### Pagination
Replace the "load more" button with a pagination menu. Pagination works by splitting the list of users into smaller chunks (pages), all of the same size. For example, if the page size is 20, the first 20 users (user 1-20) are on the first page, user 21-40 on the second page, user 41-60 on the third, and so on. There should be a pagination menu, consisting of buttons to allow navigation between the different pages.

An example for a pagination menu:
![image](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/41747605/6ca74774-877f-4cda-a3d3-c28a66bb306b)

### Filters
It is already possible to filter the user list, to display for example only users with 2FA enabled, but the current implementation is very limiting, since it allows only one filter at once. This should be changed to allow more complex queries, for example to only display enabled user accounts, that also have admin privileges, but do not have 2FA enabled (this kind of query is not possible with the current implementation).

## Acceptance criteria
- [x] The admin can select whether to search by username or by email.
- [x] Instead of the "load more" button, there is a pagination menu.
    - [x] The total number of (matching) users and the number of users on the current page are displayed.
    - [x] There are buttons for the 5 pages closest to the current page.
    - [x] There are buttons to go to the next/previous page.
    - [x] There are buttons to jump to the first/last page.
    - [x] It is possible to select the page size (10/20/50/100).
- [x] There are additional (composable) filters to only display...
    - [x] enabled/disabled users
    - [x] normal/admin users
    - [x] users with 2FA enabled/disabled
    - [x] verified/unverified users
    - [x] users who are / are not subscribed to the newsletter

**Comment by Maschga** [comment]
Is there already functionality for this in the backend, i.e. an endpoint that supports filtering and pagination?
I can't find the documentation for the API. Am I missing them or are they somewhat hidden?

**Comment by Defelo** [comment]
Yes, the functionality for this already exists in the backend. You can find the API documentation on https://api-test.bootstrap.academy/

**Comment by JohKei** [comment]
@Maschga have you already started working on this? I would like to have a Look on this ticket.

**Comment by Maschga** [comment]
Go ahead.
A few weeks ago I looked at the code and added some functionality, but in the end I decided to back out because of missing comments in the code. I didn't understand how some components behave.

**Comment by JohKei** [comment]
Today, I made the following changes:

- Implemented a functional search by name or email.
![Screenshot 2023-10-22 at 21 57 17](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/117248962/5de5129f-37c2-4b44-9b29-62f00b8abd25)
![Screenshot 2023-10-22 at 21 57 46](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/117248962/925892f6-be30-4147-b0a2-5d46c7e4030a)

- Fixed the bug that caused repeated users in the table.

I will try to implement the remaining points from the acceptance criteria by the end of next week and will keep the progress updated here.

**Comment by JohKei** [comment]
I just added a first working version of the Pagination. Got still some things to do. Will probably finish the rest by Sunday.
<img width="493" alt="Screenshot 2023-10-27 at 21 50 29" src="https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/117248962/173b2e33-0ac3-419d-9e70-97c4b40606cb">
I will be editing the style, add some space between pagination & perPage button-group's
Besides of that I'm currently only missing a functional filtering from the dropdown by User-type

**Comment by JohKei** [comment]
@Defelo its ready for reviewing

**Comment by Defelo** [comment]
Ok, thanks! I will have a look at it
