### ISSUE TITLE
Hide Quiz/Challenge buttons if there is none

### ISSUE THREAD

**Issue by DragonDev1906** [Bootstrap-Academy/Bootstrap-Academy#49]
### Bootstrap Academy username

DragonDev1906

### Description

Above a Video there are always the Video, Quiz and Challenge tabs, even if there is no Quiz or Challenge. This makes it a bit difficult to see at a glance whether there are Quizzes/Challenges.

It would be nice if the respective button is hidden (or disabled) and maybe even shows a number indicating how many Quizzes/Questions there are if it is > 0.

**Comment by Maschga** [comment]
I suggest removing buttons when a quiz or a challenge does not exist.
Furthermore I experienced with showing the number.
This is what I made:

![-](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/88616799/5d78cb20-9865-46d0-a408-194a7782fe56)
![-](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/88616799/ca7252fe-0a86-409a-87ad-6fc7685017cf)
![-](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/88616799/8e82fd26-122f-4335-979f-870c080864ba)

**Comment by DragonDev1906** [comment]
Ah, you've been a bit faster than me, I was about to have a look at it myself.

Looks good to me 👍

**Comment by Maschga** [comment]
I came over this issue and thought this would be a nice start to get in touch with this project. xD

**Comment by Maschga** [comment]
Do you want to do this issue or can I try it?

**Comment by DragonDev1906** [comment]
Feel free to have a go at it :+1:
