### ISSUE TITLE
Top menu not there on https://bootstrap.academy/challenges/leader-board

### ISSUE THREAD

**Issue by Joshiy13** [Bootstrap-Academy/Bootstrap-Academy#52]
### Bootstrap Academy username

Joshiy13

## Description

The top menu that is there on all the pages (Logo, Calendar, Skill tree, Profile picture etc.) is not on the leaderboard page.
For consistency it should probably be added.

## Showcase

![image](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/79088559/c11c5ca6-e54f-4690-945e-a0cb95d95a5f)

**Comment by TheMorpheus407** [comment]
This is also true for several other sites. The ticket is meant to fix them all. 
First of all let's find occurrences of this.

- [ ] When editing the profile
- [ ] When doing a quiz question
