### ISSUE TITLE
Translation and grammar suggestions

### ISSUE THREAD

**Issue by Sensi1707** [Bootstrap-Academy/Bootstrap-Academy#54]
### Bootstrap Academy username

sensi

### What happened?

https://bootstrap-academy-frontend.pages.dev/

[German]
![Screenshot 2023-10-08 2320411](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/103508645/29580359-4609-4e4c-a095-f96443c6a3d6)

[English]
![Screenshot 2023-10-08 231503](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/103508645/69acc50b-3b88-4947-9843-68c7f6c0c37e)

I hope I am posting this at the right place. If not, I am sorry ^^'

**Comment by Joshiy13** [comment]
I already fixes a few of those issues (I think some are live already). I believe "Is MorphCoin a cryptocurrency?" is correct though because there the singular makes more sense. I will look at the language files later today and try to fix inconsistencies.

**Comment by Joshiy13** [comment]
Issue can be closed
