### ISSUE TITLE
Skills count dont increment

### ISSUE THREAD

**Issue by 7h3Pr074g0n157** [Bootstrap-Academy/Bootstrap-Academy#55]
### Bootstrap Academy username

7heProtagonist

### Contact Details

No response

### What browsers are you seeing the problem on?

Firefox

### What happened?

At the Profilepage under "Skillpunkte" the count of Skills do not increment even if you market each Video with "als erledigt markieren".
![grafik](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/30697367/1c32b62f-a8a0-4082-a03a-3777cb7e03df)

**Comment by DragonDev1906** [comment]
I wanted to fix this (because it annoyed me, too), but given the current API response this is not possible and I cannot view or make changes to the backend.

Progress just indicates the value on the progress bar (i.e. calculated from xp). Since there is no way of knowing how high of a level can be achieved or how much XP is possible we can't know if the skill is completed (unless we'd pull that information from other endpoints which would be inefficient and error prone, that should be done in the backend).

Current API response:
```json
{
  "total_xp": 0,
  "total_level": 0,
  "progress": 1,
  "skills": [
    {
      "skill": "string",
      "xp": 0,
      "level": 0,
      "progress": 1,
      "skills": [
        {
          "skill": "string",
          "xp": 0,
          "level": 0,
          "progress": 1
        }
      ]
    }
  ]
}
```

**Comment by Defelo** [comment]
Afaik skills can no longer be "completed". I think, this is still left from when we had exams, where being able to complete skills was still a thing, but now we only have the number of xp and the level for each skill. We could of course add a threshold for when to consider a skill as "completed", but I'm not sure if this actually makes sense.

**Comment by DragonDev1906** [comment]
Wouldn't completed mean you've watched all Videos and done all quizzes? Something that could also be used in the skill tree to indicate progress (e.g. by coloring the node green).

**Comment by 7h3Pr074g0n157** [comment]
My Question would be, if completion means done all Videos and Quizzes, can the amount of Quizzes/Videos grow afterwards? 
Afaik, the Quizzes should also be made by the Community. So the amount of them is (perceptively) never final?

**Comment by RLeo** [comment]
So there is no concept for the skills? Then the display for the number of skills should be hidden until then.

Regarding the concept: I would say that a skill can also be temporary as long as you have solved all lessons and tasks, as soon as new ones are added the skill is gone. Or you can define a threshold value, e.g. 90% solved is enough for a skill.

**Comment by TheMorpheus407** [comment]
So we have in #16 an issue, that shows if there is something to do. It is not directly related to this issue, but does somehow solve the feeling, that it is not completed. 
However, i plan to bring back something like exams and there is a level cap of level 50 on a skill, which is hard to be reached at the moment. I will therefore close this issue :)
