### ISSUE TITLE
Invalid VAT ID missing error message

### ISSUE THREAD

**Issue by Forestsoft-de** [Bootstrap-Academy/Bootstrap-Academy#57]
### Bootstrap Academy username

Forest

### Contact Details

@Forestsoft-de

### What browsers are you seeing the problem on?

Chrome

### What happened?

I created an account and was redirected to the E-Mail confirmation page to enter the token.

After clicking on back i am suddently loggedin and beeing able to change my account details.

Tried to add my VAT Id  and there is an small icon:

<img width="241" alt="image" src="https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/132578/6f87e305-464e-4590-8c81-aabe263d0378">

the console shows:
<img width="419" alt="image" src="https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/132578/be35b8e2-990b-4dd8-8284-094d7eef35e0">

**Comment by Defelo** [comment]
Ok, you should be able to request a new confirmation email in your [account settings](https://bootstrap.academy/account).
