### ISSUE TITLE
Wording suggestion at a Python-Quiz-Question

### ISSUE THREAD

**Issue by 7h3Pr074g0n157** [Bootstrap-Academy/Bootstrap-Academy#61]
### Bootstrap Academy username

7heProtagonist

### Contact Details

no response

### What happened?

![grafik](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/30697367/2491eeed-c45b-4767-ab91-bffada2e6960)

Should we change the Question "Wie würde man einen String erzeugen, der den Text Sie sagte: "Hallo!" enthält? text = ?" to something like "Wie würde man einen String in der Variable text erzeugen, der wie folgt lautet: Sie sagte: "Hallo!" ". Or something else, which makes the operated String clearer.  
Or is the current formulation intentionally to be a bit more fuzzy and there is no bug?

**Comment by TheMorpheus407** [comment]
If unclear, I'd leave it to the user to report it. But you're right, using questions that cannot be misinterpreted might be better in general
