### ISSUE TITLE
Feature - Add meta for (e.g.) Discord Embeds

### ISSUE THREAD

**Issue by RafaeloxMC** [Bootstrap-Academy/Bootstrap-Academy#62]
Add meta tags so e.g. Discord will have embeds

**Comment by TheMorpheus407** [comment]
Can you explain? Where exactly and what's the intended functionality?

**Comment by RafaeloxMC** [comment]
![Screenshot_20231013-151402~2.png](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/53903394/c6ae2787-ced4-4c56-b06d-530764cd82b6)

Like this, code is pretty simple for e.g. the embeds shown in the screenshot:

```
    <meta property="og:url" content="https://xvcf.dev">
    <meta property="og:type" content="website">
    <meta property="og:title" content="@xvcf | xvcf.dev">
    <meta property="og:description" content="@xvcf's website">
    <meta property="og:image" content="https://xvcf.dev/img/og.gif">
```
