### ISSUE TITLE
Quizzes are not displayed on the "Watch Course" page

### ISSUE THREAD

**Issue by Lo10Th** [Bootstrap-Academy/Bootstrap-Academy#63]
### What browsers are you seeing the problem on?

Chrome

### What happened?

There is a problem that existing quizzes are not displayed in the "Watch Courses" view under the "Quiz" tab. I will clarify this using the video below. 

https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/70955799/eab84ec8-4f77-4b02-be68-567a78666f7d

Note that the quiz shown in the video does not seem to exist anymore. For a different example, see issue #83 by @RLeo

**Comment by JohKei** [comment]
I've found the bug. I'll create a PR on the weekend.
