### ISSUE TITLE
Empty Page after clicking on "challenges" in the top navbar

### ISSUE THREAD

**Issue by 7h3Pr074g0n157** [Bootstrap-Academy/Bootstrap-Academy#64]
### Bootstrap Academy username

7heProtagonist

### Contact Details

no response

### What browsers are you seeing the problem on?

Firefox

### What happened?

**Please notice, I already reported this issue via "Report an Issue" at the Academy. So maybe that issue can be closed.**

If you click on "Challenges" in the top navbar, you get an empty page. 
![grafik](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/30697367/83e002c6-9b27-4029-acd5-8b5ebd7e12c4)

If you click on "Challenges" in the bottom navbar (footer), you get the old challenges-site in a new tab.
![grafik](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/30697367/b7eb85d4-2c9f-4b5d-8d7b-71a1b7d2c9e4)

**Comment by Defelo** [comment]
Hi, that's actually not a bug, we just don't have any global challenges at the moment. I have created some challenge categories which will be filled later with challenges, so the page should not appear to be empty/broken anymore.

**Comment by 7h3Pr074g0n157** [comment]
This global challenges shall also be build by the community? 
If yes, where/when could I do this?

**Comment by Defelo** [comment]
Currently only administrators can create global challenges, but that will probably change so others can create global challenges as well.
