### ISSUE TITLE
No xp for completed Quiz-Question

### ISSUE THREAD

**Issue by 7h3Pr074g0n157** [Bootstrap-Academy/Bootstrap-Academy#65]
### Bootstrap Academy username

7heProtagonist

### Contact Details

no response

### What browsers are you seeing the problem on?

Firefox

### What happened?

I had 13 solved challenges in my profile and 420 xp through the videos in the “HTML and CSS” sub-skill.
Then I completed 1 question in the HTML5 course.
Now I have 14 solved challenges in my profile but in the sub-skill "HTML and CSS" still 420 xp.

![grafik](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/30697367/f7c2cfbe-7ac9-43e3-b4ef-957fd46bd55b)
![grafik](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/30697367/af107c06-7953-4cda-8363-57c2c72cda11)
![grafik](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/30697367/1dbc178c-52cd-42d6-b3e8-c0f1b6b26c44)
![grafik](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/30697367/20acd22d-7dea-47d3-8805-959e985f034b)

**Comment by 7h3Pr074g0n157** [comment]
Nope, sorry. 14 solved Challenges and xp 420 at "HTML und CSS" before and 15 solved Challenges and xp 420 at "HTML und CSS" after doing 1 Quiz at the "HTML5"-Course.

Maybe I do something wrong?

![grafik](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/30697367/0c14d468-56e7-4462-8ef9-ea80c92bc371)
![grafik](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/30697367/b7abe137-dfc3-48e0-aa03-a5fa52602393)
![grafik](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/30697367/c3127942-139e-45b3-923a-287c8b592837)
![grafik](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/30697367/cb9d6792-4196-4a20-947a-1df3bc413c5a)

**Comment by TheMorpheus407** [comment]
This needs to be evaluated.
Quiz should give 5 XP.
I am not sure about challenges though, it might be, they don't award xp right now, since it's the old interface without connection to the skills.
Can you check in the python quiz?

**Comment by 7h3Pr074g0n157** [comment]
I did just the Instruction-Challenges at the old Challenges-Webside in the beginning. Still noch challenges after releasing the Academy. 
I also assumed this statistic means both, Quizzes and actual challenges, because the number of solved increased with solved quizzes (and assumed the heading will be adjasted in the future).

I did 1 Quiz in "Python-Grundlagen". I had 16 solved at the statistic bevore and 17 after the Quiz. The xp at "Python-Grundlagen" stayed constant, 250 xp.

**Comment by TheMorpheus407** [comment]
Anyone else tested the issue?
I'm trying to gather as much info as possible

**Comment by 7h3Pr074g0n157** [comment]
I opend a related Question on dc for this and got a confirmation there.
https://discord.com/channels/326817317075943424/1165180711217664062/1167818550120022026

**Comment by 7h3Pr074g0n157** [comment]
For HTML and CSS, I set all videos to "done" and solved 4 Quizzes. I have had 420 xp and now it's 440xp.
With JS I set all videos to “done” and solved 3 quizzes. I think I have had 500 xp from the videos and now it's 515 xp.

So with 5 xp per solved quiz, getting xp for each solved Quiz seems to be fine.
