### ISSUE TITLE
Site Layouts going crazy after opening Privacy site

### ISSUE THREAD

**Issue by PackitNow** [Bootstrap-Academy/Bootstrap-Academy#66]
After opening in Firefox in Android the Privacy site of the bootstrap Academy tit is possible to Zoom Out, after that the Wohle bootstrap Academy's Layout ist going crazy.
[Demonstration video](https://youtube.com/shorts/osfBACB8eHo?feature=share)

**Comment by Naile7477** [comment]
And IT geht's worse after opening a other site
