### ISSUE TITLE
Skill tree zoom

### ISSUE THREAD

**Issue by Rotstein007** [Bootstrap-Academy/Bootstrap-Academy#70]
### Bootstrap Academy username

Rotstein

### Contact Details

rotstein_meister (discord)

### What browsers are you seeing the problem on?

Firefox

### What happened?

When you change the zoom level of the Skill tree, the text doesn't change it's size. I think it's intended to change it's size to it's zoom level. At zoom level 3x or higher, the text is too small in comparison to the rest.

**Comment by TheMorpheus407** [comment]
I think that's okay for now. We're planning to rework the entire way of the skilltree anyways. I want it to feel like Google Maps, so there's a lot of changes. But since it's no must have, I'd postpone it
