### ISSUE TITLE
Herzen freezen ein, unendlich Quizfragen :)

### ISSUE THREAD

**Issue by andi6874** [Bootstrap-Academy/Bootstrap-Academy#71]
### Bootstrap Academy username

andi6874

### Contact Details

andreas.failer02@gmail.com

### What happened?

Ich benutze Opera für die Academy (kein Opera GX!).  Übrigens leider noch keine Premium Mitgliedschaft zu dem Zeitpunkt, also die free Version.

Als ich das letzte mal in der Nacht angefangen hab, die Quizfragen zu machen, ca. 23:58 Uhr, habe ich 3 Fragen beantwortet, also standen meine Herzen bei 1,5. Als dann der neue Tag begann, also kurz nach 0 Uhr hatte ich immer noch die 1,5 Herzen. 

Zuerst war ich verwundet wiso die Herzen nicht aufgefüllt wurden, nach ein paar Fragen fiel mir auf, dass ich schon mehr als die 6 möglichen Fragen bei 3 Herzen beantwortet hatte. Zuerst hab ich vermutet dass es ein Anzeige-Bug ist (das entweder die 1,5 Herzen vom vortag + die 3 vom neuen Tag zusammengerechnet wurden, oder dass nur die 1,5 Herzen vom Vortag angezeigt werden, aber in wirklichkeit ich die 3 vom neuen Tag habe.

ABER: Auch nach mehreren Fragen locker 10 stk. veränderte sich nichts an der Herzenanzeige. 
--> Also die Herzen freezen ein, wenn man beim automatischem Auffüllen der Herzen aktiv ist, (0 Uhr)

**Comment by Defelo** [comment]
Hi, ich konnte diesen Bug bisher leider weder reproduzieren noch aus den Logs und der DB nachvollziehen. Vielleicht könntest du ja nochmal auf der [Test-Instanz](https://bootstrap-academy-frontend.pages.dev) ausprobieren, ob du das irgendwie reproduziert bekommst, und dann nochmal Bescheid sagen?

Meine erste Vermutung wäre gewesen, dass es einfach ein Anzeigefehler im Frontend ist, aber wenn du sagst, dass die Fragen danach auch alle als gelöst markiert waren (also auch nach Neuladen der Seite?), ist das vermutlich doch ein Fehler im Backend.

**Comment by andi6874** [comment]
Hi,
das selbe ist bei mir schon wieder aufgetreten. Ich werd dir mal heute
Nacht wenn ich dazu komm ein Video davon machen. Ja die Quizfragen gelten
selbst bei neuem laden der Seite als Gelöst. Auch am nächsten/übernächsten
Tag zählen diese noch als richtig beantwortet.

Beim letzten mal hab ich das sogar anderst auch hingebracht.

Ich hab die Academy ca um 10 Uhr geladen, dann auf andere Websites
gewechselt. Ohne eine einzige Frage beantwortet zu haben. Bin dann um weit
nach 12 Uhr auf die Academy zurückgewechselt. Da war das genauso wie beim
ersten mal.

Hab vlt an 3, 4 Tagen die Fragen gemacht aber viel mehr als man in der
Zeit  mit 3 Herzen machen könnte.

Wenn die Herzen freezen, tritt auch manchmal der Fehler auf, dass beim
richtig beantworten von Fragen das erste mal nicht akzeptiert wird. Beim
neu laden der Seite oder wechseln zur nächsten Frage funktioniert das dann
aber ganz normal. Das passiert aber richtig selten vlt jede 20. Aufgabe.
Theoretisch könnte man dadurch bei jeder Frage die Antwortmögligkeiten
durchprobieren.

Hoffe das war jetzt nicht zu viel Info, aber mit dem kannst du vielleicht
besser darauf schließen, und die Möglichkeiten eingrenzen.

Übrigens ich mache zurzeit den Python Kurs, denke aber nicht das das
Problem nur bei diesem Kurs besteht.

Grüße

Andi

Felix ***@***.***> schrieb am Mo., 30. Okt. 2023, 10:55:

**Comment by andi6874** [comment]
Ja, mache die Fragen immer unter dem Reiter ungelöst.  Gesendet von Mail für Windows Von: FelixGesendet: Montag, 30. Oktober 2023 16:14An: Bootstrap-Academy/Bootstrap-AcademyCc: andi6874; AuthorBetreff: Re: [Bootstrap-Academy/Bootstrap-Academy] Herzen freezen ein, unendlich Quizfragen :) (Issue #71) Hm, das ist wirklich sehr merkwürdig. Und das waren auch immer Fragen, die du vorher noch nicht beantwortet hattest? Also du hast keine Frage einfach nochmal beantwortet, nachdem du sie schon gelöst hast?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by andi6874** [comment]
Hi,hab dir jetzt ein Video aufgenommen.https://youtu.be/xgYr-tQ0MH4Alles weitere hab ich in die Beschreibung des Videos gepackt. Kp wieso es den unteren Teil vom Bild nicht aufgenommen hat(Taskleiste) aber das war wieder um 24 Uhr.  Von: FelixGesendet: Montag, 30. Oktober 2023 16:14An: Bootstrap-Academy/Bootstrap-AcademyCc: andi6874; AuthorBetreff: Re: [Bootstrap-Academy/Bootstrap-Academy] Herzen freezen ein, unendlich Quizfragen :) (Issue #71) Hm, das ist wirklich sehr merkwürdig. Und das waren auch immer Fragen, die du vorher noch nicht beantwortet hattest? Also du hast keine Frage einfach nochmal beantwortet, nachdem du sie schon gelöst hast?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Defelo** [comment]
Hi, danke für das Video. Kann es mir nur leider nicht anschauen, vermutlich ist es auf privat gestellt

**Comment by andi6874** [comment]
Hi, sorry ist mir nicht aufgefallen. Habs jetzt auf nicht gelistet gesetzt.
Da kann jeder mit dem Link das anschauen.

https://youtu.be/xgYr-tQ0MH4?si=lySl0N041BKLm0FK

Felix ***@***.***> schrieb am Di., 31. Okt. 2023, 08:44:

**Comment by andi6874** [comment]
Hi,
Nein hab kein Premium.
Am Ende des Videos sieht man auch das ich noch ein ABO abschließen könnte.

Übrigens auch wenns aussieht dass ich manche Fragen nicht beantworten kann
obwohl ich alles durchklick, funktioniert es trotzdem, nachdem man die
Seite neu lädt/ zur nächsten Frage wechselt. Wahrscheinlich habt ihr da
einen Spamm Schutz oder ähnliches eingebaut, damit man nicht taktisch alles
durch klickt.

Der ganze Bug hat bei mir jetzt schon mehrfach funktioniert.

Versuch auch mal die Seite zu laden, natürlich wenn du angemeldet bist, und
dann erst Stunden später die Fragen zu beantworten. Vlt hat das garnichts
mit der Aktualisierung um 0 Uhr zu tun, sondern dass nach mehreren Stunden
einfach die Aktualisierung der Herzen nicht mehr funktioniert, und Fehler
ausgibt?



The Morpheus Tutorials ***@***.***> schrieb am Do., 2. Nov.
2023, 12:31:

**Comment by TheMorpheus407** [comment]
Selbst wenn, im Backend wird eigentlich getestet ob du Herzen hast und es werden welche abgezogen, wenn du ne Frage löst 🤔
@Defelo könntest du da kurz gucken, muss ja eigentlich im Backend sein

**Comment by Defelo** [comment]
Ich glaube, jetzt den Fehler gefunden zu haben. Liegt vermutlich an den Timezones, da geht was bei der Berechnung des Timestamps schief, wann die Herzen aufgefüllt werden sollen. Wenn man also um Mitternacht rum die Herzen abfragt, liegt dieser Timestamp immer in der Vergangenheit, sodass jedes Mal die Herzen wieder neu aufgefüllt werden. Fix ist jetzt deployed. Wäre super, wenn du bei Gelegenheit nochmal testen könntest, ob es jetzt richtig funktioniert @andi6874

**Comment by andi6874** [comment]
Hi habs gestern Nacht nochmal ausprobiert. Jetzt funktionierts wie es soll. Danke für die Coins :)😉   Von: FelixGesendet: Donnerstag, 2. November 2023 14:53An: Bootstrap-Academy/Bootstrap-AcademyCc: andi6874; MentionBetreff: Re: [Bootstrap-Academy/Bootstrap-Academy] Herzen freezen ein, unendlich Quizfragen :) (Issue #71) Ich glaube, jetzt den Fehler gefunden zu haben. Liegt vermutlich an den Timezones, da geht was bei der Berechnung des Timestamps schief, wann die Herzen aufgefüllt werden sollen. Wenn man also um Mitternacht rum die Herzen abfragt, liegt dieser Timestamp immer in der Vergangenheit, sodass jedes Mal die Herzen wieder neu aufgefüllt werden. Fix ist jetzt deployed. Wäre super, wenn du bei Gelegenheit nochmal testen könntest, ob es jetzt richtig funktioniert @andi6874—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
