### ISSUE TITLE
Multiline solution for quizzes

### ISSUE THREAD

**Issue by Frodo1010** [Bootstrap-Academy/Bootstrap-Academy#73]
### Bootstrap Academy username

Frodo1010

### Description

I've noticed in the Clean Code playlist that it's very difficult to come up with good quizzes since one is limited to just one line. I would like to create multiple small pieces of code and ask, for example, which one is the most maintainable, or the easiest to read, and so on...

**Comment by Defelo** [comment]
Yes, we should probably allow (multiline) Markdown content in the **question** field. But I think that the **answers** should still be relatively short and in plain text only. In your specific case, you could just include the different code snippets directly in your question and then ask which code snippet of these is the "best" (e.g. code snippet A/B/C/D).

**Comment by TheMorpheus407** [comment]
Yes, let's continue the discussion in #76
