### ISSUE TITLE
Support for Multiline Markdown Support with LaTeX Formula Support

### ISSUE THREAD

**Issue by CptK** [Bootstrap-Academy/Bootstrap-Academy#76]
### Bootstrap Academy username

CptK

### Description

Implement support for LaTeX math formula rendering in quizzes. This will:

1. Enhance readability: Formulas written in LaTeX are easier to read and understand, especially for complex mathematical concepts.
2. Increase convenience: Quiz-makers can directly input LaTeX codes without having to find workarounds.

**Comment by Defelo** [comment]
I think this could be solved by adding LaTeX support directly to the Markdown rendering component (in combination with #73). It seems like there is already some (pretty bad) support for LaTeX here, this definitely needs to be fixed and improved:

![image](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/41747605/b23f7dd1-8a38-4778-bd48-1f00a2be8d73)

<details>
<summary>source</summary>

```markdown
$a^2 + b^2 = c^2$

$$\sum_{i=1}^\infty = -\frac1{12}$$
```

</details>

**Comment by TheMorpheus407** [comment]
Summary:
Provide the possibility to use Markdown including LaTeX for the quizzes.
Answers should only be one line. 
Questions should receive multiline support.

**Comment by lukaslarndorfer** [comment]
I would like to fix this Bug

**Comment by Jonathan2k19** [comment]
Hi,
I'm sorry, I didn't see that someone else was assigned to the ticket before I started working on it.
I still shared my attempt to fix (parts of) the issue [this PR](https://github.com/Bootstrap-Academy/frontend/pull/290), in case it is helpful to @LLarndorfer.
Just to be clear, I won't continue to work on it from now on, as someone else is officially assigned to it.

**Comment by NilocLP** [comment]
> Summary: Provide the possibility to use Markdown including LaTeX for the quizzes. Answers should only be one line. Questions should receive multiline support.

"I think it would be useful to include a small info when creating a quiz question, explaining how to format or implement LaTeX code inside the question. Something like a span with a link to the KaTeX documentation.

**Comment by LLarndorfer** [comment]
If @Jonathan2k19 liked, he could finish this issue.

**Comment by lukaslarndorfer** [comment]
@Defelo what's the current state of the issue? Did this [pull](https://github.com/Bootstrap-Academy/frontend/pull/290) fix it or is there still a part missing?
Greetings

**Comment by Defelo** [comment]
Yes, I think this has been fixed, thanks for the reminder
