### ISSUE TITLE
"NoQuizFoundForYouToSolve"-Answer although there is a quiz

### ISSUE THREAD

**Issue by RLeo** [Bootstrap-Academy/Bootstrap-Academy#83]
### Bootstrap Academy username

LeoR

### What happened?

When viewing individual lessons, no associated quizzes are displayed, only the "NoQuizFoundForYouToSolve" message.
Example: https://bootstrap.academy/courses/javascript/watch?section=section&lecture=LGefU5nrQbg
But there is a quiz in the json that comes from the backend:
` https://api.bootstrap.academy/challenges/courses/javascript/tasks?lecture_id=LGefU5nrQbg&section_id=section `
``` json
[
    {
        "course_id": "javascript",
        "id": "c353c9c5-116c-450d-a956-eb744d365930",
        "lecture_id": "LGefU5nrQbg",
        "section_id": "section"
    }
]
```

`https://api.bootstrap.academy/challenges/tasks/c353c9c5-116c-450d-a956-eb744d365930/multiple_choice`
``` json
[
    {
        "coins": 0,
        "creation_timestamp": "2023-10-21T11:40:34.280414+00:00",
        "creator": "b00ca1ab-89c3-413b-a8ed-6d8b2305333d",
        "enabled": true,
        "id": "4b93fd2b-2b66-4bea-aac8-61a505bb1690",
        "question": "Welcher der folgenden Werte wird NICHT dem Wert \"false\" gleichgesetzt?",
        "rated": false,
        "retired": false,
        "single_choice": true,
        "solved": false,
        "task_id": "c353c9c5-116c-450d-a956-eb744d365930",
        "type": "MULTIPLE_CHOICE_QUESTION",
        "xp": 5
    }
]
```

**Comment by RLeo** [comment]
It could be the same error as #63 
However, you cannot see in the video whether the quiz is also assigned to this lesson. When I try to recreate this, I can't find any quiz in the lesson "java_algorithmen"

**Comment by Defelo** [comment]
> It could be the same error as #63

Yes, you're right, that's probably the same bug. I will close this ticket in favor of #63.

> However, you cannot see in the video whether the quiz is also assigned to this lesson. When I try to recreate this, I can't find any quiz in the lesson "java_algorithmen"

Yup, this quiz does not seem to exist anymore. I have added a reference in #63 to this issue to provide a different example there.
