### ISSUE TITLE
Typo in "Job Details"

### ISSUE THREAD

**Issue by Toubson27** [Bootstrap-Academy/Bootstrap-Academy#87]
### Bootstrap Academy username

S3mu

### Contact Details

tobias.blair27@gmail.com

### What browsers are you seeing the problem on?

Other (please specify below)

### What happened?

Browser: Brave v. 1.60.114

https://bootstrap.academy/jobs/f6dd7748-38e5-4792-b762-2df57005a1f9

Diverse Schreib und Grammatikfehler in der Job-Beschreibung.

Verbesserungsvorschlag für Copy-Paste-Korrektur:
___________________________________________________

Du möchtest Teil eines Teams werden und Scrum aktiv kennen lernen? Dann bist du bei uns genau richtig. Du brauchst keine Vorerfahrungen oder besondere Fähigkeiten. Nur etwas Zeit und Lust zu lernen.

Gemeinsam mit einem Team entwickelst du in deiner Freizeit einen Skillbereich, lernst dabei das Light-Framework Scrum kennen und hilfst anderen, es zu verstehen.

Nach einer angemessenen Zeit bescheinigt dir das Team auch gerne, dass du erste Erfahrungen in Scrum gesammelt hast. Was deine Karrierechancen in dieser Richtung wirklich verbessern kann.

Worauf wartest du noch? Melde dich jetzt und schau dir das Ganze gerne einmal unverbindlich an. Jede/r ist herzlich willkommen.

Als Belohnung winkt sogar ein Erfahrungsbericht von Scrum Trainer Steffen Rohrer.

**Comment by TheMorpheus407** [comment]
Job offers are part of the community content. We shouldn't make it our responsibility to take care of their typos :)
