### ISSUE TITLE
Implement Coaching feature

### ISSUE THREAD

**Issue by JohKei** [Bootstrap-Academy/Bootstrap-Academy#88]
### Bootstrap Academy username

Joggl

### Description

Currently, the Bootstrap-Academy website lacks the ability to create, update, and manage coachings. The backend lacks the necessary routes to handle coaching data, and the frontend is missing the corresponding views for creating and editing coachings.Right now there's no way to create or edit a Coaching event in the Frontend even tough this is a key-feature of this page. [The Backend seems to lack of routes for creating Coaching & Editing Coaching.](https://api-test.bootstrap.academy/events/redoc#tag/coachings)

1. ### Backend
    - Create routes for creating and updating Coachings. 
2. ### Frontend
    - Develop a page for creating new coachings.
    - Create a page for editing existing coachings. 
    - implement the ability to create a coaching on the button in the user profile under the chosen skill. 
    
![CreateCoachingButton](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/117248962/dcd66a63-5ba4-4598-868b-52737ea157f2)

**Comment by TheMorpheus407** [comment]
Coachings will be an entirely new feature, which I already have an idea for. But we'll postpone that, since there are things that are more ciritcal.
