### ISSUE TITLE
Issues with self-hosted videos

### ISSUE THREAD

**Issue by Defelo** [Bootstrap-Academy/Bootstrap-Academy#9]
Some of the self-hosted videos don't seem to work properly in all browsers. *Maybe* this has been fixed lately by converting all videos to h264, but this definetly needs more testing and debugging.

This is a list of courses which contain self-hosted videos:
- https://bootstrap.academy/courses/pentesting_grundlagen
- https://bootstrap.academy/courses/nmap
- https://bootstrap.academy/courses/password_cracking
- https://bootstrap.academy/courses/python_hacking
- https://bootstrap.academy/courses/schwachstellen_web_anwendungen

For everyone who has intel on this issue - if it works or if the issue persists, please comment down below, so we can gather more info on what this is all about. We can award you for that with small amounts of MorphCoin and can get a better grasp on the problem.

**Comment by DimitReeis** [comment]
Seems to work on my end. No problems on Firefox, Chrome and Edge on windows 11

**Comment by TheMorpheus407** [comment]
Occurrence reported on gleap:


### Browser Information:

- **Browser Name:** Firefox(118.0)
- **User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
- **Browser:** Firefox
- **System Name:** Windows
- **Session Duration:** 00:27:54
- **Device Pixel Ratio:** 1.25
- **Screen Width:** 1536px
- **Screen Height:** 864px
- **Inner Width:** 1536px
- **Inner Height:** 864px
- **URL:** [Pentesting Grundlagen Course](https://bootstrap.academy/courses/pentesting_grundlagen/watch?section=section&lecture=was_tun_hacker&skillID=pentester&subSkillID=grundlagen_des_pentesting)
- **Language:** de

### Logs:

#### Network Logs:

- `18:06:09` [FETCH](https://api.bootstrap.academy/challenges/tasks/9ba6fe64-75a6-4487-bfed-30fd45ad01a9/multiple_choice) 
- `18:06:09` [FETCH](https://api.bootstrap.academy/challenges/courses/pentesting_grundlagen/tasks) 
- `18:06:08` [FETCH](https://api.bootstrap.academy/auth/session)
- `...`

#### Event Logs:

- `18:06:08` pageView [Pentesting Grundlagen](https://bootstrap.academy/courses/pentesting_grundlagen?section=section5&lecture=pentesting_15_zugriff_bekommen&skillID=pentester&subSkillID=grundlagen_des_pentesting)
- `18:06:00` pageView [Pentesting Grundlagen - Was tun Hacker](https://bootstrap.academy/courses/pentesting_grundlagen/watch?section=section&lecture=was_tun_hacker&skillID=pentester&subSkillID=grundlagen_des_pentesting)
- `...` 

#### Console Logs:

- `18:06:00` Click: `<svg class="w-5 h-5 rotate-180 text-subheading"></svg>`
- `18:05:58` Click: `<svg class="w-5 h-5 rotate-0 text-accent"></svg>`
- `...`

**Comment by webseppel** [comment]
Just tested it and had two issues with the video [Pentesting Grundlagen - Was tun Hacker](https://bootstrap.academy/courses/pentesting_grundlagen/watch?section=section&lecture=was_tun_hacker)

### System Information

- OS: Windows 10 Pro 22H2
- Browser: Firefox 118.0.2 (64-Bit)

### Issues

1. I klicked the videotimeline a few times to see if there are any issues. Sometimes the video turned half black as seen in the screenshot below. It fixed itself after a few seconds. This could be reproduced every 2-3 times I skipped a part in the video.

![bootstrap_academy_halfblack](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/62438618/22d172b2-73a6-434a-8206-42f0a639e3b2)

2. After doing a little more of skipping I got an error as seen below. In the console I found the following error:
`Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.` 

![2023-10-17 11_14_04-Watch Course - Pentesting Grundlagen – Mozilla Firefox](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/62438618/98e0f4ee-eba4-4c76-a39f-7504f979ffbf)

This could also be reproduced.

Time of Testing: Tue, 17 Oct 2023 ~ 09:15:00 - 09:30:00 GMT

**Comment by Thomas-Winter-sar** [comment]
https://bootstrap.academy/courses/pentesting_grundlagen works fine with Firefox 119.0 on Win 10

**Comment by Defelo** [comment]
I just pushed a few changes in https://github.com/Bootstrap-Academy/skills-ms/pull/251, which should hopefully fix most of these issues, so I will close this for now. If you are still having problems with the self-hosted videos, please [open a new issue](https://github.com/Bootstrap-Academy/Bootstrap-Academy/issues/new/choose).
