### ISSUE TITLE
On /skill-tree/progress: Skill is not classified as an active skill when a level is reached

### ISSUE THREAD

**Issue by RLeo** [Bootstrap-Academy/Bootstrap-Academy#90]
### Bootstrap Academy username

LeoR

### What happened?

![image](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/11270911/f5ab238e-110e-4ba2-822d-8d5806573293)
Level and XP in the skill indicate an active skill, not the % rate in the progress bar.

**Comment by TheMorpheus407** [comment]
The % in the progress bar should ideally indicate your progress for the level up. So let's say, you're Level 42 in a skill. You have 2000 XP, you needed 1000 XP in total to reach Level 42 and you need 3000 for level 43, then the bar should be at half.
