### ISSUE TITLE
Small white pixels

### ISSUE THREAD

**Issue by Lauritz-Tieste** [Bootstrap-Academy/Bootstrap-Academy#97]
### Bootstrap Academy username

Lauritz

### What browsers are you seeing the problem on?

Microsoft
Error not happening in firefox

### What happened?

Small white pixels appear on some pages of Bootstrap Academy. These serve no purpose, can't be clicked or anything like that. These are probably leftovers from debugging or development

![image](https://github.com/Bootstrap-Academy/Bootstrap-Academy/assets/84938977/b3dc7516-2fad-439f-86fb-158a0cb47274)

**Comment by TheMorpheus407** [comment]
I just noticed. These might be the scroll bars?

**Comment by Lauritz-Tieste** [comment]
The white pixels are not clickable or draggable. As you see in the right picture, there is already a green scrollbar, but a white pixel in the corner.

**Comment by PascalThelke** [comment]
How does it work to get assignet? I might have a fix for the problem, but i am a also a Jr.

**Comment by Lauritz-Tieste** [comment]
I think you can start with the ticket, and @Defelo will assign you soon
