### ISSUE TITLE
Make the Academy installable as a Progressive Web App

### ISSUE THREAD

**Issue by Lauritz-Tieste** [Bootstrap-Academy/Bootstrap-Academy#99]
### Bootstrap Academy username

Lauritz

### Description

With almost all operating systems and web browsers, there is the possibility to install a website as an app or link it to the home screen. If you then open the app, but unfortunately the browser search provider is still displayed. This can be fixed by creating/changing the `manifest.json` file.

https://www.jsdiaries.com/how-to-hide-address-bar-in-a-progressive-web-application/

**Comment by TheMorpheus407** [comment]
Go ahead :)
Thanks for the idea!

**Comment by Lauritz-Tieste** [comment]
https://github.com/Bootstrap-Academy/frontend/pull/129 is ready for review
